version: '3'
services:
  bd:
    image: mongo
    container_name: mongo
  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - "bd"
    ports:
      - "4201:4201"
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    env_file:
      - variables.env
    depends_on:
      - "back"
    ports:
      - "8267:80"
networks:
  app-network:
    driver: bridge
